###
# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#


【活跃】816陈嘉禄186386621 8:01:11
13，陈嘉禄，201616010417，已完成

【团支书】510丁婷婷15649861801 8:23:38
14,丁婷婷，
201616010429，已完成

【管理员】807郭田雨156397827 8:46:15
15,郭田雨，
201616010216，已完成

【吐槽】815涂文奇157388969 8:47:11
16,涂文奇，201616010410，已完成

【冒泡】511李琳琳156496816 8:48:39
17,李琳琳，201616010330，已完成

【组织委员】807徐向阳156498625 8:50:23
 18、徐向阳，201616010212，已完成

【活跃】510殷少伟18037212798 8:55:38
 19、殷少伟，201616010428，已完成

【冒泡】812何双营131643907 9:08:12
20,何双营，201616010320,已完成

【冒泡】813胡定鹏156498677 9:17:30
21,胡定鹏，201616010324,已完成

【冒泡】816王少宇131643892 9:24:16
22、王少宇，201616010414，已完成


# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
#----------------------------------------property------------------------------------------------###
###
GET http://localhost:8080/admin/property/list?pageNo=1&pageSize=10&companyId=1
Accept: application/json

###--------------------delete--------------
GET http://localhost:8080/admin/property/delete?id=4c7b2cd411982974a8d2bc597846c3d0
Accept: application/json

###--------------------detail-------------
GET http://localhost:8080/admin/property/detail?name=address
Accept: application/json

###--------------------list-------------
POST http://localhost:8080/admin/property/list
Content-Type: application/json

{
  "pageNo":1,
  "pageSize":10,
  "companyId": "111111"
}


###--------------------edit-------------
POST http://localhost:8080/admin/property/edit
Content-Type: application/json

{
  "id": "50f53b3d337a5db32e8d14ebaa3c4d50",
  "name": "address",
  "canEdit": 1,
  "code": "1",
  "orderNum":9999,
  "companyId":"1",
  "type": 0
}
###--------------add---------------------
POST http://localhost:8080/admin/property/add
Content-Type: application/json

{
  "name": "address",
  "canEdit": 1,
  "orderNum":999,
  "companyId":"2343134242414121412412414124124141421412",
  "type": 0
}

###--------------edit---------------------
POST http://localhost:8080/admin/property/edit
Content-Type: application/json

{

  "id": "dc4aa3cfbcebefd28f5c3fd7dc63ff8e",
   "name": "联系电话",
   "orderNum": 5,
  "isSearch": 1,
  "isSearchKey":1
}

###--------------edit---------------------
POST http://localhost:8080/admin/property/edit
Content-Type: application/json

{
"name": "addreaawdawdawdwawdawdwadawdawdawdwadawdadawdwadwadwadwadwadwass",
"canEdit": 1,
"code": "1",
"orderNum":999,
"companyId":"1",
"type": 0
}
###
GET http://localhost:8080/admin/property/queryDetail?id=11b6f22704f40170f0127de55d12819e
Accept: application/json


###------------------------------------------industry-----------------------------------------------------###
#--------------add---------------------
POST http://localhost:8080/admin/industry/add
Content-Type: application/json

{
  "name": "制造业",
  "belong": 1
}

###-----------------------delete------------------
GET http://localhost:8080/admin/industry/delete?id=f40399d38104155d69ec8cbc8acba642
Accept: application/json

###--------------queryList---------------------
GET http://localhost:8080/admin/industry/queryDetail?id=1c9cf2910bc83690c0e3d1bf14e8cf53
Accept: application/json

###--------------queryList---------------------
GET http://localhost:8080/admin/industry/queryList?pageNo=1&pageSize=10&belong=1
Accept: application/json

###--------------edit---------------------
POST http://localhost:8080/admin/industry/edit
Content-Type: application/json

{
  "id": "1c9cf2910bc83690c0e3d1bf14e8cf53",
  "name": "制造2业"
}
###

POST http://localhost:8080/admin/enterprisOrOrgan/queryList
Content-Type: application/json

{
  "pageNo": 1,
  "pageSize": 10,
  "belong": 1
}
###
